#The API ID in API Manager    
api:
 id: "17674105"

jsonLogger: 
  disabledFields: "content"
  maskedFields: ""

http:
  "host": "0.0.0.0"
  "port": "8081"

walmart:
  sys:
    host : "walmart-sys-api.us-e2.cloudhub.io"
    port : "80"
    reconnectionAttempts : "3"
    frequency : "2000" 
    timeout: "60000"
    path:
      getProductsPath: "/api/products"
      getProductsOrderId: "/api/products/{orderId}"